package io.hexlet;

import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.SQLOutput;

public class Application {
    // Нужно указывать базовое исключение,
    // потому что выполнение запросов может привести к исключениям
    public static void main(String[] args) throws SQLException {
        // Создаем соединение с базой в памяти
        // База создается прямо во время выполнения этой строчки
        // mem выбирает базу в памяти, hexlet_test задаёт её имя
        var conn = DriverManager.getConnection("jdbc:h2:mem:hexlet_test");

        var sql =
                "CREATE TABLE users (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                        + " username VARCHAR(255), phone VARCHAR(255))";
        // Чтобы выполнить запрос, создадим объект statement
        var statement = conn.createStatement();
        statement.execute(sql);
        statement.close(); // В конце закрываем

        var sql2 = "INSERT INTO users (username, phone) VALUES ('tommy', '123456789'), ('maria', '987654321')";
        var statement2 = conn.createStatement();
        statement2.executeUpdate(sql2);
        statement2.close();

        var sql3 = "SELECT * FROM users ORDER BY id";
        var statement3 = conn.createStatement();
        // Получаем результат запроса
        var resultSet = statement3.executeQuery(sql3);
        // next() перемещает курсор к следующей строке результата
        while (resultSet.next()) {
            System.out.print(resultSet.getLong("id") + " ");
            System.out.print(resultSet.getString("username") + " ");
            System.out.print(resultSet.getString("phone") + " ");
            System.out.println();
        }
        statement3.close();

        // Закрываем соединение
        conn.close();
    }
}