package io.hexlet;

import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.SQLOutput;
import java.sql.Statement;

public class Application {

    public static void main(String[] args) throws SQLException {
        try (var conn = DriverManager.getConnection("jdbc:h2:mem:dao")) {
            try (var statement = conn.createStatement()) {
                statement.executeUpdate(
                        """
                            CREATE TABLE users (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                username VARCHAR(255),
                                phone VARCHAR(255)
                            )
                            """);

            }

            var dao = new UserDAO(conn);
            var user = new User("Maria", "888888888");
            System.out.println("User id: " + user.getId());
            dao.save(user);
            System.out.println("User id: " + user.getId());
            var user2 = new User("Alex", "899899899");
            dao.save(user2);

            user.setPhone("999999999");
            dao.save(user);

            System.out.println("Удален пользователь: " + user.getName() + " " + dao.delete(user.getId()));
            System.out.println("Удален пользователь: " + user.getName() + " " + dao.delete(user.getId()));

            var savedUser = dao.find(user2.getId()).orElseThrow();
            System.out.println(savedUser.getId().equals(user.getId()));
            System.out.println(savedUser.getPhone());
            System.out.println(dao.find(99L).isEmpty());
        }
    }
}