package io.hexlet;

import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.SQLOutput;
import java.sql.Statement;

public class Application {

    public static void main(String[] args) throws SQLException {

        try (var conn = DriverManager.getConnection("jdbc:h2:mem:hexlet_test")) {

            var sql =
                    "CREATE TABLE users (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                            + " username VARCHAR(255), phone VARCHAR(255))";
            // Чтобы выполнить запрос, создадим объект statement
            try (var statement = conn.createStatement()) {
                statement.execute(sql);
            }

            var sql2 = "INSERT INTO users (username, phone) VALUES (?, ?)";
            try (var preparedStatement = conn.prepareStatement(sql2, Statement.RETURN_GENERATED_KEYS)) {
                preparedStatement.setString(1, "Sarah");
                preparedStatement.setString(2, "333333333");
                preparedStatement.executeUpdate();

                preparedStatement.setString(1, "Tommy");
                preparedStatement.setString(2, "444444444");
                preparedStatement.executeUpdate();

                preparedStatement.setString(1, "O'Connor");
                preparedStatement.setString(2, "555555555");
                preparedStatement.executeUpdate();

                try (var generatedKeys = preparedStatement.getGeneratedKeys()) {
                    while (generatedKeys.next()) {
                        System.out.println(
                                generatedKeys.getInt(1)
                        );

                        var sqlDelete = "DELETE FROM users WHERE username = ?";
                        try (var statementDelite = conn.prepareStatement(sqlDelete, Statement.RETURN_GENERATED_KEYS)) {
                            statementDelite.setString(1, "O'Connor");
                            statementDelite.executeUpdate();
                        }
                    }
                }
            }

            var sql3 = "SELECT * FROM users ORDER BY id";
            try (var statement3 = conn.createStatement()) {
                // Получаем результат запроса
                var resultSet = statement3.executeQuery(sql3);
                // next() перемещает курсор к следующей строке результата
                while (resultSet.next()) {
                    System.out.printf("%s %s %s\n",
                            resultSet.getLong("id"),
                            resultSet.getString("username"),
                            resultSet.getString("phone")
                    );
                }
            }
        }
    }
}